const fs = require('fs');

const file = 'workflows/17-ai-generate-text.json';
const workflow = JSON.parse(fs.readFileSync(file, 'utf8'));
const attempt = workflow.nodes.find((node) => node.name === 'Prepare Provider Attempt');
const internal = workflow.nodes.find((node) => node.name === 'Prepare Internal Request');
attempt.parameters.jsCode = "const input = $input.first()?.json ?? {};\nconst retryCount = Number(input.retryCount || 0);\nconst uuidV4 = () => { const bytes = new Uint8Array(16); for (let i = 0; i < bytes.length; i++) bytes[i] = Math.floor(Math.random() * 256); bytes[6] = (bytes[6] & 0x0f) | 0x40; bytes[8] = (bytes[8] & 0x3f) | 0x80; return Array.from(bytes, byte => byte.toString(16).padStart(2, '0')).join('').replace(/^(........)(....)(....)(....)(............)$/, '$1-$2-$3-$4-$5'); };\nconst requestId = retryCount > 0 || !input.requestId ? uuidV4() : input.requestId;\nreturn [{ json: { ...input, retryCount, requestId } }];";
internal.parameters.jsCode = "const input = $('Prepare Provider Attempt').last()?.json ?? $('Workflow Trigger').first()?.json ?? {};\nconst source = input.source && typeof input.source === 'object' ? input.source : {};\nconst body = source.body && typeof source.body === 'object' && !Array.isArray(source.body) ? source.body : {};\nconst metadata = Object.prototype.hasOwnProperty.call(source, 'metadata') ? source.metadata : body.metadata;\nconst jobId = input.jobId ?? source.jobId ?? source.job_id ?? metadata?.jobId ?? metadata?.job_id ?? 'unknown-job';\nconst uuidV4 = () => { const bytes = new Uint8Array(16); for (let i = 0; i < bytes.length; i++) bytes[i] = Math.floor(Math.random() * 256); bytes[6] = (bytes[6] & 0x0f) | 0x40; bytes[8] = (bytes[8] & 0x3f) | 0x80; return Array.from(bytes, byte => byte.toString(16).padStart(2, '0')).join('').replace(/^(........)(....)(....)(....)(............)$/, '$1-$2-$3-$4-$5'); };\nconst requestId = input.requestId ?? uuidV4();\nconst providerId = input.provider ?? source.provider ?? body.provider ?? $env.AI_TEXT_PROVIDER ?? 'cloudflare';\nconst credentialSource = input.credentialSource ?? 'environment';\nconst modelId = input.modelId ?? source.modelId ?? body.modelId ?? $env.CLOUDFLARE_TEXT_MODEL ?? 'gemini-2.5-flash';\nreturn [{ json: { jobId: String(jobId), requestId: String(requestId), providerId: String(providerId), modelId: String(modelId), credentialSource: String(credentialSource), routingVersion: String(input.routingVersion || '1'), prompt: String(input.prompt ?? source.prompt ?? body.prompt ?? ''), systemPrompt: input.systemPrompt ?? source.systemPrompt ?? body.systemPrompt ?? '', temperature: Number(input.temperature ?? 0.6), maxOutputTokens: Number(input.maxOutputTokens ?? 5000), responseFormat: String(input.responseFormat ?? 'text'), timeoutMs: Number(input.timeoutMs ?? 30000) } }];";
fs.writeFileSync(file, `${JSON.stringify(workflow, null, 2)}\n`);
console.log(file);
